import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Adilson
 */
public class FrameCliente extends javax.swing.JFrame {
    Tutor tutor = new Tutor();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form FrameCliente
     */
    public FrameCliente() {
        initComponents();
        setSize(862,518);
        setIcon();
        setLocation(300,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbNomeCliente = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        lbTelefoneCliente = new javax.swing.JLabel();
        ftfTelefoneCliente = new javax.swing.JFormattedTextField();
        lbCelularCliente = new javax.swing.JLabel();
        ftfCelularCliente = new javax.swing.JFormattedTextField();
        lbTelefoneRecadoCliente = new javax.swing.JLabel();
        ftfTelefoneRecadoCliente = new javax.swing.JFormattedTextField();
        lbEnderecoCliente = new javax.swing.JLabel();
        tfEnderecoCliente = new javax.swing.JTextField();
        lbNumeroEnderecoCliente = new javax.swing.JLabel();
        tfNumeroEnderecoCliente = new javax.swing.JTextField();
        lbBairroCliente = new javax.swing.JLabel();
        tfBairroCliente = new javax.swing.JTextField();
        lbCidadeCliente = new javax.swing.JLabel();
        tfCidadeCliente = new javax.swing.JTextField();
        lbUfCliente = new javax.swing.JLabel();
        cbUfCliente = new javax.swing.JComboBox<>();
        lbCepCliente = new javax.swing.JLabel();
        ftfCepCliente = new javax.swing.JFormattedTextField();
        lbProfissaoCliente = new javax.swing.JLabel();
        tfProfissaoCliente = new javax.swing.JTextField();
        lbRendaCliente = new javax.swing.JLabel();
        tfRendaCliente = new javax.swing.JTextField();
        lbNascimento = new javax.swing.JLabel();
        ftfNascimento = new javax.swing.JFormattedTextField();
        lbRgCliente = new javax.swing.JLabel();
        ftfRgCliente = new javax.swing.JFormattedTextField();
        lbCpfCliente = new javax.swing.JLabel();
        ftfCpfCliente = new javax.swing.JFormattedTextField();
        lbEmailCliente = new javax.swing.JLabel();
        tfEmailCliente = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btMeuPet = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        lbFundoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Tutor Pet");
        setMinimumSize(new java.awt.Dimension(862, 490));

        jPanel2.setLayout(null);

        lbNomeCliente.setText("Nome");
        jPanel2.add(lbNomeCliente);
        lbNomeCliente.setBounds(47, 39, 50, 14);
        jPanel2.add(tfNomeCliente);
        tfNomeCliente.setBounds(47, 59, 320, 27);

        lbTelefoneCliente.setText("Telefone");
        jPanel2.add(lbTelefoneCliente);
        lbTelefoneCliente.setBounds(412, 39, 60, 14);

        try {
            ftfTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefoneCliente.setToolTipText("");
        jPanel2.add(ftfTelefoneCliente);
        ftfTelefoneCliente.setBounds(412, 59, 100, 27);

        lbCelularCliente.setText("Celular");
        jPanel2.add(lbCelularCliente);
        lbCelularCliente.setBounds(539, 39, 50, 14);

        try {
            ftfCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftfCelularCliente);
        ftfCelularCliente.setBounds(539, 59, 110, 27);

        lbTelefoneRecadoCliente.setText("Recado");
        jPanel2.add(lbTelefoneRecadoCliente);
        lbTelefoneRecadoCliente.setBounds(676, 39, 50, 14);

        try {
            ftfTelefoneRecadoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftfTelefoneRecadoCliente);
        ftfTelefoneRecadoCliente.setBounds(676, 59, 100, 27);

        lbEnderecoCliente.setText("Endereço");
        jPanel2.add(lbEnderecoCliente);
        lbEnderecoCliente.setBounds(47, 97, 60, 14);
        jPanel2.add(tfEnderecoCliente);
        tfEnderecoCliente.setBounds(47, 117, 395, 27);

        lbNumeroEnderecoCliente.setText("Número");
        jPanel2.add(lbNumeroEnderecoCliente);
        lbNumeroEnderecoCliente.setBounds(460, 97, 60, 14);
        jPanel2.add(tfNumeroEnderecoCliente);
        tfNumeroEnderecoCliente.setBounds(460, 117, 68, 27);

        lbBairroCliente.setText("Bairro");
        jPanel2.add(lbBairroCliente);
        lbBairroCliente.setBounds(546, 97, 50, 14);
        jPanel2.add(tfBairroCliente);
        tfBairroCliente.setBounds(546, 117, 230, 27);

        lbCidadeCliente.setText("Cidade");
        jPanel2.add(lbCidadeCliente);
        lbCidadeCliente.setBounds(47, 155, 50, 14);
        jPanel2.add(tfCidadeCliente);
        tfCidadeCliente.setBounds(47, 175, 254, 27);

        lbUfCliente.setText("UF");
        jPanel2.add(lbUfCliente);
        lbUfCliente.setBounds(319, 155, 20, 14);

        cbUfCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbUfCliente.setToolTipText("");
        jPanel2.add(cbUfCliente);
        cbUfCliente.setBounds(311, 175, 55, 27);

        lbCepCliente.setText("CEP");
        jPanel2.add(lbCepCliente);
        lbCepCliente.setBounds(377, 155, 40, 14);

        try {
            ftfCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftfCepCliente);
        ftfCepCliente.setBounds(377, 175, 77, 27);

        lbProfissaoCliente.setText("Profissão");
        jPanel2.add(lbProfissaoCliente);
        lbProfissaoCliente.setBounds(472, 155, 80, 14);
        jPanel2.add(tfProfissaoCliente);
        tfProfissaoCliente.setBounds(472, 175, 206, 27);

        lbRendaCliente.setText("Renda");
        jPanel2.add(lbRendaCliente);
        lbRendaCliente.setBounds(696, 155, 50, 14);
        jPanel2.add(tfRendaCliente);
        tfRendaCliente.setBounds(696, 175, 81, 27);

        lbNascimento.setText("Nascimento");
        jPanel2.add(lbNascimento);
        lbNascimento.setBounds(47, 213, 80, 14);

        try {
            ftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfNascimentoActionPerformed(evt);
            }
        });
        jPanel2.add(ftfNascimento);
        ftfNascimento.setBounds(47, 235, 118, 27);

        lbRgCliente.setText("RG");
        jPanel2.add(lbRgCliente);
        lbRgCliente.setBounds(183, 213, 30, 14);

        try {
            ftfRgCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftfRgCliente);
        ftfRgCliente.setBounds(183, 235, 86, 27);

        lbCpfCliente.setText("CPF");
        jPanel2.add(lbCpfCliente);
        lbCpfCliente.setBounds(287, 213, 40, 14);

        try {
            ftfCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftfCpfCliente);
        ftfCpfCliente.setBounds(287, 235, 117, 27);

        lbEmailCliente.setText("Email");
        jPanel2.add(lbEmailCliente);
        lbEmailCliente.setBounds(422, 213, 50, 14);
        jPanel2.add(tfEmailCliente);
        tfEmailCliente.setBounds(422, 235, 355, 27);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btSalvar);
        btSalvar.setBounds(50, 393, 70, 27);

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(btConsultar);
        btConsultar.setBounds(140, 393, 90, 27);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btEditar);
        btEditar.setBounds(260, 393, 61, 27);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir);
        btExcluir.setBounds(360, 393, 70, 27);

        btMeuPet.setText("Meu Pet");
        btMeuPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMeuPetActionPerformed(evt);
            }
        });
        jPanel2.add(btMeuPet);
        btMeuPet.setBounds(520, 393, 80, 27);

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(btVoltar);
        btVoltar.setBounds(720, 393, 61, 27);

        lbFundoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotoFundoFrameProprietario.png"))); // NOI18N
        jPanel2.add(lbFundoCliente);
        lbFundoCliente.setBounds(0, 0, 860, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMeuPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMeuPetActionPerformed
        FramePet framePet = new FramePet();
        framePet.setVisible(true);
    }//GEN-LAST:event_btMeuPetActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
        
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
               
        tutor.setNome(tfNomeCliente.getText());
        tutor.setTelefone(ftfTelefoneCliente.getText());
        tutor.setCelular(ftfCelularCliente.getText());
        tutor.setRecado(ftfTelefoneRecadoCliente.getText());
        tutor.setEndereco(tfEnderecoCliente.getText());
        tutor.setNunEnd(Integer.parseInt(tfNumeroEnderecoCliente.getText()));
        tutor.setBairro(tfBairroCliente.getText());
        tutor.setCidade(tfCidadeCliente.getText());
        tutor.setUf((String)cbUfCliente.getSelectedItem());
        tutor.setCep(ftfCepCliente.getText());
        tutor.setProfissao(tfProfissaoCliente.getText());
        tutor.setRenda(Float.parseFloat(tfRendaCliente.getText()));
        try {
            tutor.setNascimento(formato.parse(ftfNascimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        tutor.setRg(ftfRgCliente.getText());
        tutor.setCpf(ftfCpfCliente.getText());
        tutor.setEmail(tfEmailCliente.getText());
        
          
        try {
            salvarCliente(tutor);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        FramePet framePet = new FramePet();
        framePet.setVisible(true);
        
    }//GEN-LAST:event_btSalvarActionPerformed

    
     //Método para estabelecer conexão com o BD Derby
    
    public Connection getConnection() throws ClassNotFoundException, SQLException{
        String driveJDBC = "org.apache.derby.jdbc.Driver42";
        String url = "jdbc:derby://localhost:1527/LovePetP1";
        String usuario = "Adilson";
        String senha = "chacal";
        
        Connection connection;
        Class.forName(driveJDBC);
        connection = (Connection) DriverManager.getConnection(url, usuario, senha);
        return connection;
    }
    
    //Método para salvar (gravar) os dados do cliente no BD
     private void salvarCliente(Tutor cli) throws SQLException, ClassNotFoundException {
        Connection connection = getConnection();
        Statement stmt;
        stmt = connection.createStatement();// executa um comeando SQL
        
        String nome = cli.getNome();
        String telefone = cli.getTelefone();
        String celular = cli.getCelular();
        String recado = cli.getRecado();
        String endereco = cli.getEndereco();
        int numEndereco = cli.getNunEnd();
        String bairro = cli.getBairro();
        String cidade = cli.getCidade();
        String estado = cli.getUf();
        String cep = cli.getCep();
        String profissao = cli.getProfissao();
        float renda = cli.getRenda();
        String nascimento = formato.format(cli.getNascimento());
        String rg = cli.getRg();
        String cpf = cli.getCpf();
        String email = cli.getEmail();
                
        String sql = "INSERT INTO tutor (nome, telefone, celular, recado, endereco,"
                +"numend, bairro, cidade, uf, cep, profissao, renda, nascimento, rg,"
                +"cpf, email) VALUES ('"+nome+"','"+telefone+"','"+celular+"','"+recado
                +"','"+endereco+"',"+numEndereco+",'"+bairro+"','"+cidade+"','"+estado
                +"','"+cep+"','"+profissao+"',"+renda+",'"+nascimento+"','"+rg+"','"+cpf+"','"+email+"')";
        
        stmt.executeUpdate(sql);
                
       JOptionPane.showMessageDialog(null,"Dados salvo com sucesso!!!");
       
       limparCampo();
    }
     
     public void buscarTutorNome() throws ClassNotFoundException, SQLException{
        Connection connection;
        connection = getConnection();
        Statement stmt;
        ResultSet rs;
        
        stmt = connection.createStatement();
        
        String sql;
        sql = "Select * from tutor Where (nome Like Trim('%"+tfNomeCliente.getText()+"%'))";
        rs = stmt.executeQuery(sql);
        rs.next();
        
        tfNomeCliente.setText(rs.getString(1));        
        ftfTelefoneCliente.setText(rs.getString(2));        
        ftfCelularCliente.setText(rs.getString(3));        
        ftfTelefoneRecadoCliente.setText(rs.getString(4));        
        tfEnderecoCliente.setText(rs.getString(5));        
        tfNumeroEnderecoCliente.setText(String.valueOf(rs.getInt(6)));        
        tfBairroCliente.setText(rs.getString(7));        
        tfCidadeCliente.setText(rs.getString(8));        
        cbUfCliente.setSelectedItem(rs.getString(9));        
        ftfCepCliente.setText(rs.getString(10));        
        tfProfissaoCliente.setText(rs.getString(11));        
        tfRendaCliente.setText(String.valueOf(rs.getFloat(12)));        
        ftfNascimento.setText(rs.getString(13));        
        ftfRgCliente.setText(rs.getString(14));        
        ftfCpfCliente.setText(rs.getString(15));        
        tfEmailCliente.setText(rs.getString(16));        
     }
     
     //Metodo para bloquear os campos do frame
     public void bloquearCampos(){
         tfNomeCliente.setEditable(false);
         ftfTelefoneCliente.setEditable(false);
         ftfCelularCliente.setEditable(false);
         ftfTelefoneRecadoCliente.setEditable(false);
         tfEnderecoCliente.setEditable(false);
         tfNumeroEnderecoCliente.setEditable(false);
         tfBairroCliente.setEditable(false);
         tfCidadeCliente.setEditable(false);
         cbUfCliente.setEnabled(false);
         ftfCepCliente.setEditable(false);
         tfProfissaoCliente.setEditable(false);
         tfRendaCliente.setEditable(false);
         ftfNascimento.setEditable(false);
         ftfRgCliente.setEditable(false);
         ftfCpfCliente.setEditable(false);
         tfEmailCliente.setEditable(false);
     }
     
     //Metodo para desbloquear campos do frame
     public void desbloquearCampos(){
         tfNomeCliente.setEditable(true);
         ftfTelefoneCliente.setEditable(true);
         ftfCelularCliente.setEditable(true);
         ftfTelefoneRecadoCliente.setEditable(true);
         tfEnderecoCliente.setEditable(true);
         tfNumeroEnderecoCliente.setEditable(true);
         tfBairroCliente.setEditable(true);
         tfCidadeCliente.setEditable(true);
         cbUfCliente.setEnabled(true);
         ftfCepCliente.setEditable(true);
         tfProfissaoCliente.setEditable(true);
         tfRendaCliente.setEditable(true);
         ftfNascimento.setEditable(true);
         ftfRgCliente.setEditable(true);
         ftfCpfCliente.setEditable(true);
         tfEmailCliente.setEditable(true);
     }
     
     
     public void excluirTutorPet() throws ClassNotFoundException, SQLException{
         Connection connection;
         connection = getConnection();
         Statement stmt;
         
         stmt = connection.createStatement();
         
         String sql;
         sql = "Delete from tutor Where (nome = '"+tfNomeCliente.getText()+"')";
         stmt.executeUpdate(sql);
         
         limparCampo();
         
         JOptionPane.showMessageDialog(null, "DADOS DO TUTOR EXCLUÍDO COM SUCESSO!!!", "CONFIRMAÇÃO DE EXCLUSÃO", HEIGHT);
     }
     
     //Metodo para editar campos do frame
     public void editarTutor(Tutor tut) throws ClassNotFoundException, SQLException{
         //desbloquearCampos();
         
        Connection connection = getConnection();
        Statement stmt;
        stmt = connection.createStatement();// executa um comeando SQL
        
        String nome = tut.getNome();
        String telefone = tut.getTelefone();
        String celular = tut.getCelular();
        String recado = tut.getRecado();
        String endereco = tut.getEndereco();
        int numEndereco = tut.getNunEnd();
        String bairro = tut.getBairro();
        String cidade = tut.getCidade();
        String estado = tut.getUf();
        String cep = tut.getCep();
        String profissao = tut.getProfissao();
        float renda = tut.getRenda();
        String nascimento = formato.format(tut.getNascimento());
        String rg = tut.getRg();
        String cpf = tut.getCpf();
        String email = tut.getEmail();
                
        String sql = "UPDATE tutor SET nome='"+nome+"', telefone='"+telefone
                +"', celular='"+celular+"', recado='"+recado+"', endereco='"
                +endereco+"', numend="+numEndereco+", bairro='"+bairro+"', cidade='"
                +cidade+"', uf='"+estado+"', cep='"+cep+"', profissao='"+profissao
                +"',"+ " renda="+renda+", nascimento='"+nascimento+"', rg='"+rg
                +"', cpf='"+cpf+"', email='"+email+"' WHERE nome = '"+tfNomeCliente.getText()+"'";

        stmt.executeUpdate(sql);
                
       JOptionPane.showMessageDialog(null,"Dados salvo com sucesso!!!");
       
       limparCampo();
         
     }
     
     
     //Metodo para limpar todos os campos do frame
     public void limparCampo() {
         tfNomeCliente.setText("");
         ftfTelefoneCliente.setText("");
         ftfCelularCliente.setText("");
         ftfTelefoneRecadoCliente.setText("");
         tfEnderecoCliente.setText("");
         tfNumeroEnderecoCliente.setText("");
         tfBairroCliente.setText("");
         tfCidadeCliente.setText("");
         cbUfCliente.setSelectedIndex(-1);
         ftfCepCliente.setText("");
         tfProfissaoCliente.setText("");
         tfRendaCliente.setText("");
         ftfNascimento.setText("");
         ftfRgCliente.setText("");
         ftfCpfCliente.setText("");
         tfEmailCliente.setText("");
         
     }
    
    private void ftfNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfNascimentoActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        
        try {
            buscarTutorNome();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        //bloquearCampos();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            excluirTutorPet();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        tutor.setNome(tfNomeCliente.getText());
        tutor.setTelefone(ftfTelefoneCliente.getText());
        tutor.setCelular(ftfCelularCliente.getText());
        tutor.setRecado(ftfTelefoneRecadoCliente.getText());
        tutor.setEndereco(tfEnderecoCliente.getText());
        tutor.setNunEnd(Integer.parseInt(tfNumeroEnderecoCliente.getText()));
        tutor.setBairro(tfBairroCliente.getText());
        tutor.setCidade(tfCidadeCliente.getText());
        tutor.setUf((String)cbUfCliente.getSelectedItem());
        tutor.setCep(ftfCepCliente.getText());
        tutor.setProfissao(tfProfissaoCliente.getText());
        tutor.setRenda(Float.parseFloat(tfRendaCliente.getText()));
        try {
            tutor.setNascimento(formato.parse(ftfNascimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        tutor.setRg(ftfRgCliente.getText());
        tutor.setCpf(ftfCpfCliente.getText());
        tutor.setEmail(tfEmailCliente.getText());
        
        
        try {
            editarTutor(tutor);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, UnsupportedLookAndFeelException, IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconCadastro.png")));
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btMeuPet;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbUfCliente;
    private javax.swing.JFormattedTextField ftfCelularCliente;
    private javax.swing.JFormattedTextField ftfCepCliente;
    private javax.swing.JFormattedTextField ftfCpfCliente;
    private javax.swing.JFormattedTextField ftfNascimento;
    private javax.swing.JFormattedTextField ftfRgCliente;
    private javax.swing.JFormattedTextField ftfTelefoneCliente;
    private javax.swing.JFormattedTextField ftfTelefoneRecadoCliente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBairroCliente;
    private javax.swing.JLabel lbCelularCliente;
    private javax.swing.JLabel lbCepCliente;
    private javax.swing.JLabel lbCidadeCliente;
    private javax.swing.JLabel lbCpfCliente;
    private javax.swing.JLabel lbEmailCliente;
    private javax.swing.JLabel lbEnderecoCliente;
    private javax.swing.JLabel lbFundoCliente;
    private javax.swing.JLabel lbNascimento;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbNumeroEnderecoCliente;
    private javax.swing.JLabel lbProfissaoCliente;
    private javax.swing.JLabel lbRendaCliente;
    private javax.swing.JLabel lbRgCliente;
    private javax.swing.JLabel lbTelefoneCliente;
    private javax.swing.JLabel lbTelefoneRecadoCliente;
    private javax.swing.JLabel lbUfCliente;
    private javax.swing.JTextField tfBairroCliente;
    private javax.swing.JTextField tfCidadeCliente;
    private javax.swing.JTextField tfEmailCliente;
    private javax.swing.JTextField tfEnderecoCliente;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfNumeroEnderecoCliente;
    private javax.swing.JTextField tfProfissaoCliente;
    private javax.swing.JTextField tfRendaCliente;
    // End of variables declaration//GEN-END:variables
}
