
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adilson
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setIcon();
        setLocation(180,80);
        setResizable(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        painelFramePrincipal = new javax.swing.JPanel();
        lbBoasVindas = new javax.swing.JLabel();
        btIniciar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lbFotoFramePrincipal = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setMaximumSize(new java.awt.Dimension(862, 490));
        setMinimumSize(new java.awt.Dimension(862, 490));

        painelFramePrincipal.setMaximumSize(new java.awt.Dimension(862, 490));
        painelFramePrincipal.setMinimumSize(new java.awt.Dimension(862, 490));
        painelFramePrincipal.setLayout(null);

        lbBoasVindas.setFont(new java.awt.Font("CommercialScript BT", 0, 48)); // NOI18N
        lbBoasVindas.setForeground(new java.awt.Color(115, 115, 216));
        lbBoasVindas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBoasVindas.setText("Bem Vindo ao LovePet");
        painelFramePrincipal.add(lbBoasVindas);
        lbBoasVindas.setBounds(0, 20, 860, 60);

        btIniciar.setText("Iniciar");
        btIniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });
        painelFramePrincipal.add(btIniciar);
        btIniciar.setBounds(720, 360, 90, 40);

        btSair.setText("Sair");
        btSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSair.setMaximumSize(new java.awt.Dimension(35, 21));
        btSair.setMinimumSize(new java.awt.Dimension(35, 21));
        btSair.setPreferredSize(new java.awt.Dimension(35, 21));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        painelFramePrincipal.add(btSair);
        btSair.setBounds(90, 360, 90, 40);

        lbFotoFramePrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pets1.jpg"))); // NOI18N
        lbFotoFramePrincipal.setMaximumSize(new java.awt.Dimension(862, 490));
        lbFotoFramePrincipal.setMinimumSize(new java.awt.Dimension(862, 490));
        lbFotoFramePrincipal.setPreferredSize(new java.awt.Dimension(862, 490));
        painelFramePrincipal.add(lbFotoFramePrincipal);
        lbFotoFramePrincipal.setBounds(0, 0, 862, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFramePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFramePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        FrameCliente frameCliente = new FrameCliente();
        frameCliente.setVisible(true);
    }//GEN-LAST:event_btIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lbBoasVindas;
    private javax.swing.JLabel lbFotoFramePrincipal;
    private javax.swing.JPanel painelFramePrincipal;
    // End of variables declaration//GEN-END:variables

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("casaPet.png")));
    }
}
