/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adilson
 */
public class FrameMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public FrameMenuPrincipal() {
        initComponents();
        setLocation(300,150);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundodeTela = new javax.swing.JPanel();
        lbFundoDeTela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItem = new javax.swing.JMenu();
        menuItemSalvar = new javax.swing.JMenuItem();
        menuItemExcluir = new javax.swing.JMenuItem();
        menuItemLocalizar = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuItempessoa = new javax.swing.JMenuItem();
        submenuPessoaMenuClientes = new javax.swing.JMenu();
        itemFisicaSubMenuPessoaMenuCliente = new javax.swing.JMenuItem();
        itemJuridicaSubMenuPessoaMenucliente = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuItemFornecedor = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuItemGeral = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbFundoDeTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paisagem-natural.jpg"))); // NOI18N
        lbFundoDeTela.setText("figura");

        javax.swing.GroupLayout painelFundodeTelaLayout = new javax.swing.GroupLayout(painelFundodeTela);
        painelFundodeTela.setLayout(painelFundodeTelaLayout);
        painelFundodeTelaLayout.setHorizontalGroup(
            painelFundodeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundodeTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFundoDeTela, javax.swing.GroupLayout.PREFERRED_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelFundodeTelaLayout.setVerticalGroup(
            painelFundodeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundodeTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFundoDeTela, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuItem.setMnemonic('A');
        menuItem.setText("Arquivo");

        menuItemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalvar.setText("Salvar");
        menuItem.add(menuItemSalvar);

        menuItemExcluir.setText("Excluir");
        menuItem.add(menuItemExcluir);

        menuItemLocalizar.setText("Localizar");
        menuItem.add(menuItemLocalizar);

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuItem.add(menuItemSair);

        jMenuBar1.add(menuItem);

        menuEditar.setMnemonic('E');
        menuEditar.setText("Editar");
        jMenuBar1.add(menuEditar);

        menuClientes.setMnemonic('C');
        menuClientes.setText("Cliente");
        menuClientes.setToolTipText("Operações com clientes");

        menuItempessoa.setText("Cadastro");
        menuClientes.add(menuItempessoa);

        submenuPessoaMenuClientes.setText("Pessoa");

        itemFisicaSubMenuPessoaMenuCliente.setText("Pessoa Física");
        itemFisicaSubMenuPessoaMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFisicaSubMenuPessoaMenuClienteActionPerformed(evt);
            }
        });
        submenuPessoaMenuClientes.add(itemFisicaSubMenuPessoaMenuCliente);

        itemJuridicaSubMenuPessoaMenucliente.setText("Pessoa Juridica");
        itemJuridicaSubMenuPessoaMenucliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJuridicaSubMenuPessoaMenuclienteActionPerformed(evt);
            }
        });
        submenuPessoaMenuClientes.add(itemJuridicaSubMenuPessoaMenucliente);

        menuClientes.add(submenuPessoaMenuClientes);

        jMenuBar1.add(menuClientes);

        menuRelatorio.setMnemonic('R');
        menuRelatorio.setText("Relatorio");

        menuItemClientes.setText("Clientes");

        jMenuItem3.setText("jMenuItem3");
        menuItemClientes.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        menuItemClientes.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        menuItemClientes.add(jMenuItem5);

        menuRelatorio.add(menuItemClientes);

        menuItemFornecedor.setText("Fornecedores");

        jMenuItem7.setText("jMenuItem7");
        menuItemFornecedor.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        menuItemFornecedor.add(jMenuItem8);

        menuRelatorio.add(menuItemFornecedor);

        menuItemGeral.setText("Geral");

        jMenuItem9.setText("jMenuItem9");
        menuItemGeral.add(jMenuItem9);

        menuRelatorio.add(menuItemGeral);

        jMenuBar1.add(menuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundodeTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundodeTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemJuridicaSubMenuPessoaMenuclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJuridicaSubMenuPessoaMenuclienteActionPerformed
        // Codigo para chamar a janela de pessoa juridica
        FramePessoaJuridica framePessoaJuridica = new FramePessoaJuridica();
        framePessoaJuridica.setVisible(true);
    }//GEN-LAST:event_itemJuridicaSubMenuPessoaMenuclienteActionPerformed

    private void itemFisicaSubMenuPessoaMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFisicaSubMenuPessoaMenuClienteActionPerformed
        // TODO add your handling code here:
        FramePessoaFisica framePessoaFisica = new FramePessoaFisica();
        framePessoaFisica.setVisible(true);
    }//GEN-LAST:event_itemFisicaSubMenuPessoaMenuClienteActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemFisicaSubMenuPessoaMenuCliente;
    private javax.swing.JMenuItem itemJuridicaSubMenuPessoaMenucliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lbFundoDeTela;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuItem;
    private javax.swing.JMenu menuItemClientes;
    private javax.swing.JMenuItem menuItemExcluir;
    private javax.swing.JMenu menuItemFornecedor;
    private javax.swing.JMenu menuItemGeral;
    private javax.swing.JMenuItem menuItemLocalizar;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSalvar;
    private javax.swing.JMenuItem menuItempessoa;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JPanel painelFundodeTela;
    private javax.swing.JMenu submenuPessoaMenuClientes;
    // End of variables declaration//GEN-END:variables
}
